export const USER_UPDATE = 'USER_UPDATE';
export const USER_EMAIL_SENT = 'USER_EMAIL_SENT';
export const USER_HYDRATE = 'USER_HYDRATE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_DECREMENT_UNSEEN_REPORTS_COUNT = 'USER_DECREMENT_UNSEEN_REPORTS_COUNT';
